name: assignment1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24
  - pandas>=2.0
  - scikit-learn>=1.3
  - scipy>=1.11
  - matplotlib-inline
  - ipython
  - ipykernel
  - jupyter_client
  - jupyter_core
  - joblib
  - psutil
  - pip
  - setuptools
  - wheel
  - packaging
  - typing_extensions
  - traitlets
  - prompt-toolkit
  - pygments
  - tornado
  - tzdata
  - ca-certificates
  - openssl
  - sqlite
  - zlib
  - xz
  - tk
  - pip:
      - bottleneck
      - numexpr